export const UserActionTypes = {

    SET_STATE : "SET_STATE" ,
    SET_FIRSTNAME : "SET_FIRSTNAME" ,
    SET_LASTNAME : "SET_LASTNAME" ,
    SET_USERNAME : "SET_USERNAME" ,
    SET_EMAIL : "SET_EMAIL" ,
    SET_PASSWORD : "SET_PASSWORD" ,
    SET_AVATAR : "SET_AVATAR" ,

};