name: Heroku Deploy

on:
  push:
    branches:
      - main  
      - develop

  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sharpsfront" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}